- hosts: media
  sudo: yes
  vars:
    download_dir: /opt
  tasks:
  - name: be sure each module are installed.
    yum: name={{ item }} state=latest
    with_items:
        - libX11
        - gsm-devel
        - libXext
        - libXfixes
        - openjpeg
        - libvorbis
        - opencv
        - alsa-plugins-speex
        - SDL

#  - name: be sure each rpms are download.
#    command: curl -L -o "{{download_dir}}/{{item}}" https://mirror.its.sfu.ca/mirror/CentOS-Third-Party/atrpms/el6-x86_64/stable/{{item}}
#    with_items:
#        - ffmpeg-2.2.1-65.el6.x86_64.rpm
#        - libavcodec55-2.2.1-65.el6.x86_64.rpm
#        - libavdevice55-2.2.1-65.el6.x86_64.rpm
#        - libavfilter4-2.2.1-65.el6.x86_64.rpm
#        - libavformat55-2.2.1-65.el6.x86_64.rpm
#        - libavutil52-2.2.1-65.el6.x86_64.rpm
#        - libmp3lame0-3.99.3-23.el6.x86_64.rpm
#        - libopencore-amrnb0-0.1.3-1.el6.x86_64.rpm
#        - libopencore-amrwb0-0.1.3-1.el6.x86_64.rpm
#        - libpostproc52-2.2.1-65.el6.x86_64.rpm
#        - librtmp0-2.3-1.el6.x86_64.rpm
#        - libswresample0-2.2.1-65.el6.x86_64.rpm
#        - libswscale2-2.2.1-65.el6.x86_64.rpm
#        - libva-1.3.1-11.el6.x86_64.rpm
#        - libva-devel-1.3.1-11.el6.x86_64.rpm
#        - libva-drm1-1.3.1-11.el6.x86_64.rpm
#        - libva-x11_1-1.3.1-11.el6.x86_64.rpm
#        - libva1-1.3.1-11.el6.x86_64.rpm
#        - libvdpau1-0.7-5.el6.x86_64.rpm
#        - libx264_142-0.142-20_20140406.2245.el6.x86_64.rpm
#        - libxavs1-0.1.51-2.el6.x86_64.rpm
#        - libxvidcore4-1.3.2-15.el6.x86_64.rpm
#        - libavcodec55-2.2.1-65.el6.x86_64.rpm
#        - libmp3lame0-3.99.3-23.el6.x86_64.rpm
#        - libvpx-1.0.0-1.el6.x86_64.rpm
#        - libavdevice55-2.2.1-65.el6.x86_64.rpm

  - name: be sure each rpm are installed.
    command: rpm -Uvh {{download_dir}}/{{item}}
    with_items:
        - libavutil52-2.2.1-65.el6.x86_64.rpm
        - libx264_142-0.142-20_20140406.2245.el6.x86_64.rpm
        - libxavs1-0.1.51-2.el6.x86_64.rpm
        - libxvidcore4-1.3.2-15.el6.x86_64.rpm
        - libopencore-amrnb0-0.1.3-1.el6.x86_64.rpm
        - libopencore-amrwb0-0.1.3-1.el6.x86_64.rpm
        - libva1-1.3.1-11.el6.x86_64.rpm
        - libva-x11_1-1.3.1-11.el6.x86_64.rpm
        - libva-drm1-1.3.1-11.el6.x86_64.rpm
        - libva-1.3.1-11.el6.x86_64.rpm
        - librtmp0-2.3-1.el6.x86_64.rpm
        - libmp3lame0-3.99.3-23.el6.x86_64.rpm
        - libvpx-1.0.0-1.el6.x86_64.rpm
        - libavcodec55-2.2.1-65.el6.x86_64.rpm
        - libavformat55-2.2.1-65.el6.x86_64.rpm
        - libpostproc52-2.2.1-65.el6.x86_64.rpm
        - libswresample0-2.2.1-65.el6.x86_64.rpm
        - libswscale2-2.2.1-65.el6.x86_64.rpm
        - libavfilter4-2.2.1-65.el6.x86_64.rpm
        - libavdevice55-2.2.1-65.el6.x86_64.rpm
        - libvdpau1-0.7-5.el6.x86_64.rpm
        - ffmpeg-2.2.1-65.el6.x86_64.rpm
