---
- hosts: web
  sudo: yes
  tasks:
    - name: Install libselinux-python
      yum: name=libselinux-python state=installed
    - name: disable SELinux
      sudo: yes
      selinux: state=disabled
