- hosts: web
  sudo: yes
  tasks:
    - name: be sure httpd is installed
      yum: name=httpd state=installed
    - name: be sure php is installed
      yum: name={{item}} state=installed enablerepo=remi
      with_items:
          - php55-php
          - php55-php-mbstring
    - name: be sure httpd is installed
      yum: name=httpd state=installed
    #- name: be sure httpd is running and enabled
    #  service: name=httpd state=running enabled=yes
- hosts: db
  sudo: yes
  tasks:
    - name: be sure Redis is installed.
      yum: name=redis state=installed enablerepo=remi
    - name: be sure mysqld is installed.
      yum: name=mysql-server state=installed
    - name: be sure mysql is installed.
      yum: name=mysql state=installed
