    - name:  be sure register the repositories.
      yum: name={{item}} state=present
      with_items:
         - http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
         - http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
         - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm

    - name: get the Jenkins Repository.
      get_url: url=http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo
    - name: add the Jenkins Repository.
      rpm_key: key=http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key

    - name: be sure change the repository state disable
      replace: dest=/etc/yum.repos.d/{{item}} regexp="enabled *=*1" replace="enabled=0"
      with_items:
         - epel.repo
         - rpmforge.repo
         - remi.repo
         - jenkins.repo
